# ===============================
# APP CONFIG
# ===============================
spring.application.name=real-estate-spring-boot-app
server.port=3060

# ===============================
# DATABASE CONFIG (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/propertydealer?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# ===============================
# JWT CONFIG
# ===============================
jwt.secret=AshokNagar@SecureJWTKey2026VeryStrongSecret123
jwt.expirationMs=86400000

# ===============================
# SMS CONFIG (MSG91)
# ===============================
sms.api.url=https://api.msg91.com/api/v5/otp
sms.api.key=YOUR_SMS_API_KEY
sms.sender.id=PRDEAL

# ===============================
# ADMIN EMAILS
# ===============================
app.admin.emails=admin1@example.com,admin2@example.com

# ===============================
# MAIL CONFIG (GMAIL SMTP)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=udaymahajan1000@gmail.com
spring.mail.password=bmdrtipgkolvxywm

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true
# ===============================
# FILE UPLOAD
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# ===============================
# OTHER SETTINGS
# ===============================
spring.main.allow-bean-definition-overriding=true
springdoc.override-with-generic-response=false